# config.yaml

time:
  dt_minutes: 15
  horizon_hours: 24

battery:
  e_nom_kwh: 10.0
  soc_min: 0.1
  soc_max: 0.9
  p_ch_max_kw: 4.0
  p_dis_max_kw: 4.0
  eta_ch: 0.95
  eta_dis: 0.95
  replacement_cost_gbp: 3500

pv:
  p_dc_stc_kw: 5.0
  annual_deg_rate: 0.01   # 1%/year
  temp_coeff_per_c: 0.004
  t_ref_c: 25.0

economics:
  lambda_batt: 1.0     # battery degradation weight
  lambda_pv: 0.5       # PV degradation weight
  lambda_carbon: 0.0   # carbon cost weight

